name: filedog
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  android_id: ^0.3.4
  #appinio_video_player: ^1.2.2
  #better_player_plus: ^1.0.5
  #better_player: ^0.0.83
  chewie: ^1.7.4
  #cloud_firestore: ^4.13.2
  crypto: ^3.0.3
  cryptography: ^2.5.0
  cryptography_flutter: ^2.3.0
  cupertino_icons: ^1.0.4
  date_format: ^2.0.7
  device_info_plus: ^9.0.3
  dio: ^5.4.0
  dots_indicator: ^3.0.0
  exif: ^3.2.1
  extended_image: ^8.2.0
  ffmpeg_kit_flutter: 5.1.0
  file_picker: ^6.1.1
  filesystem_picker: ^4.1.0
  #flutter_audio_waveforms: ^1.2.1+4

  #firebase_core: ^2.22.0
  #firebase_auth: ^4.15.0
  #firebase_dynamic_links: ^5.4.6
  flutter_easyloading: ^3.0.5
  #flutter_native_splash: ^2.3.1
  flutter_pdfview: ^1.3.2
  flutter_quill: ^9.2.5
  flutter_secure_storage: ^9.0.0
  flutter_speed_dial: ^7.0.0
  get: ^4.6.6
  google_sign_in: ^5.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0
  image: ^4.0.15
  image_gallery_saver: ^2.0.3
  intl_utils: ^2.8.4
  just_audio: ^0.9.35
  local_auth: ^2.1.7
  path: ^1.8.3
  path_provider: ^2.0.11
  pin_code_fields: ^8.0.1
  percent_indicator: ^4.2.2
  permission_handler: ^11.1.0
  share_plus: ^7.2.1
  shared_preferences: ^2.1.1
  uuid: ^4.3.2
  webview_flutter: ^4.2.4
  wechat_assets_picker: ^9.0.0-dev.2
  wechat_camera_picker: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.5
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - html-js/docxtest.html
    - html-js/exceltest.html
    - html-js/jsandcss/jquery-3.6.0.min.js
    - html-js/jsandcss/xlsx.full.min.js
    - html-js/jsandcss/mammoth.browser.min.js
    - html-js/jsandcss/bootstrap.min.css
    - images/guide-1.png
    - images/login.png
    - images/background_1280.jpg
    - images/default-photo-directory-2.png
    - images/default-image.png
    - images/unknow-photo-118.png
    - images/sad-face.png
    - images/calclock.png
    - images/filedoglogo.png
    - images/empty-folder.png
    - images/loading.gif
    - images/unknown.png
    - images/docx.png
    - images/pdf.png
    - images/txt.png
    - images/xlsx.png
    - images/notepad.png
    - images/mp3.png
    - images/music.png
    - images/sound-wave.png
    - images/facebook_logo.png
    - images/google_logo.png
    - images/twitter_logo.png
    - images/email_icon.png
    - images/authsuccess.png
    - images/authfail.png
    - images/photofolder-1.png
    - images/photofolder-2.png
    - images/photofolder-3.png
    - images/movefile.png
    - images/documents.png
    - images/casestte-1280.png
    - images/defaultfoldernaming.png
    - images/2.0x/default-photo-directory-2.png
    - images/2.0x/unknow-photo-118.png
    - images/2.0x/sad-face.png
    - images/2.0x/calclock.png
    - images/2.0x/emptyfolder.png
    - images/2.0x/loading.gif
    - images/2.0x/unknown.png
    - images/3.0x/default-photo-directory-2.png
    - images/3.0x/unknow-photo-118.png
    - images/3.0x/sad-face.png
    - images/3.0x/calclock.png
    - images/3.0x/emptyfolder.png
    - images/3.0x/loading.gif
    - images/3.0x/unknown.png
    - images/icons/edit.png
    - images/icons/read_only.png
    - images/icons/selectall.png
    - images/icons/unselectall.png
    - images/icons/move.png
    - images/icons/download.png
    - images/lottie/trash-bin.json
    - images/lottie/empty-box.json
    - images/lottie/sign-in-green.json
    - images/lottie/voice-wave.json
    - images/lottie/sign-out.json

    # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyIcons
      fonts:
        - asset: fonts/MyIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true

flutter_icons:
  image_path: 'images/filedog-logo.png'
  android: "launcher_icon"
  ios: true
